<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Faq extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Faq_model');
        $this->load->library('form_validation');        
	   $this->load->library('datatables');
        $this->load->model('Cek_login');
        $this->Cek_login->is_admin();
    }

    public function index()
    {
        $this->slice->view('admin/faq/faq_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Faq_model->json();
    }

    public function read($id) 
    {
        $row = $this->Faq_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'question' => $row->question,
		'answer' => $row->answer,
	    );
            $this->slice->view('admin/faq/faq_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/faq'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('admin/faq/create_action'),
	    'id' => set_value('id'),
	    'question' => set_value('question'),
	    'answer' => set_value('answer'),
	);
        $this->slice->view('admin/faq/faq_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'question' => $this->input->post('question',TRUE),
		'answer' => $this->input->post('answer',TRUE),
	    );

            $this->Faq_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('admin/faq'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Faq_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('admin/faq/update_action'),
        		'id' => set_value('id', $row->id),
        		'question' => set_value('question', $row->question),
        		'answer' => set_value('answer', $row->answer),
	    );
            $this->slice->view('admin/faq/faq_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/faq'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'question' => $this->input->post('question',TRUE),
		'answer' => $this->input->post('answer',TRUE),
	    );

            $this->Faq_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('admin/faq'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Faq_model->get_by_id($id);

        if ($row) {
            $this->Faq_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('admin/faq'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/faq'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('question', 'question', 'trim|required');
	$this->form_validation->set_rules('answer', 'answer', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Faq.php */
/* Location: ./application/controllers/Faq.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-07-28 08:20:19 */
/* http://harviacode.com */