<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Files extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Files_model');
        $this->load->library('form_validation');        
	    $this->load->library('datatables');
        $this->load->model('Upload_model');
    }

    public function index()
    {
        $this->slice->view('admin/files/files_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Files_model->json();
    }

    public function read($id) 
    {
        $row = $this->Files_model->get_by_id($id);
        if ($row) {
            $data = array(
    		'id' => $row->id,
    		'file' => $row->file,
	    );
            $this->slice->view('admin/files/files_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/files'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('admin/files/create_action'),
    	    'id' => set_value('id'),
    	    'file' => set_value('file'),
	       );
        $this->slice->view('admin/files/files_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $files = '';
            if(!empty($_FILES['file']['name'])){
                $file = $this->Upload_model->upload_files('assets/document/','swu_doc',$_FILES['file']);
                // echo '<pre>';
                // print_r($file);
                // echo '</pre>';
                // exit;
                $files = $file;
            }
            $data = array(
		      'file' => $files,
	        );
            //print_r($_FILES['file']);
            //echo $files;
            $this->Files_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('admin/files'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Files_model->get_by_id($id);

            if ($row) {
                $data = array(
                    'button' => 'Update',
                    'action' => site_url('admin/files/update_action'),
            		'id' => set_value('id', $row->id),
            		'file' => set_value('file', $row->file),
    	    );
            $this->slice->view('admin/files/files_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/files'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		    'file' => $this->input->post('file',TRUE),
	    );

            $this->Files_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('admin/files'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Files_model->get_by_id($id);

        if ($row) {
            @unlink(site_url('assets/document/').$row->file);
            $this->Files_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('admin/files'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/files'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('file', 'file', 'trim');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Files.php */
/* Location: ./application/controllers/Files.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-08-16 09:26:06 */
/* http://harviacode.com */