<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Campus_hiring_model extends CI_Model
{

    public $table = 'campus_hiring';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,judul,isi,tgl,status');
        $this->datatables->from('campus_hiring');
        //add this line for join
        //$this->datatables->join('table2', 'campus_hiring.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('admin/campus_hiring/close/$1'),'Tutup').' | '.anchor(site_url('campus_hiring/read/$1'),'Read')." | ".anchor(site_url('campus_hiring/update/$1'),'Update')." | ".anchor(site_url('campus_hiring/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('judul', $q);
	$this->db->or_like('isi', $q);
	$this->db->or_like('tgl', $q);
	$this->db->or_like('status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('judul', $q);
	$this->db->or_like('isi', $q);
	$this->db->or_like('tgl', $q);
	$this->db->or_like('status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
    public function get_current_page_records($limit, $start) 
    {
        $this->db->limit($limit, $start);
        $query = $this->db->get("campus_hiring");
 
        if ($query->num_rows() > 0) 
        {
            foreach ($query->result() as $row) 
            {
                $data[] = $row;
            }
             
            return $data;
        }
 
        return false;
    }
    
    public function get_total() 
    {
        return $this->db->count_all("campus_hiring");
    }
}

/* End of file Campus_hiring_model.php */
/* Location: ./application/models/Campus_hiring_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-07-20 04:35:08 */
/* http://harviacode.com */