<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Gallery_model extends CI_Model
{

    public $table = 'gallery';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,title,description');
        $this->datatables->from('gallery');
        //add this line for join
        //$this->datatables->join('table2', 'gallery.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('admin/gallery/read/$1'),'<span class="btn btn-primary">Read</span>')." ".anchor(site_url('admin/gallery/update/$1'),'<span class="btn btn-warning">Edit</span>')." ".anchor(site_url('admin/gallery/delete/$1'),'<span class="btn btn-danger">Delete</span>','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }
    // datatables
    function jsongambar() {
        $this->datatables->select('ig.id as id,ig.title,ig.images,g.title as album');
        $this->datatables->from('images_gallery as ig');
        //add this line for join
        $this->datatables->join('gallery as g', 'g.id = ig.id_gallery','left');
        $this->datatables->add_column('action', anchor(site_url('admin/gallery/delete_gambar/$1'),'<span class="btn btn-danger">Delete</span>','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    function get_all_data(){
        $this->db->order_by('id', 'desc');
        return $this->db->get('gallery')->result();
    }
    // get all
    function get_all()
    {
        $this->db->order_by('id', 'desc');
        $result = $this->db->get('gallery')->result();

        $data = array();
        foreach ($result as $row) {
            $data[] = array(
                    'id'=>$row->id,
                    'title'=>$row->title,
                    'description'=>$row->description,
                    'gambar'=>$this->get_gambar($row->id),
                );
        }

        return $data;
    }
    // get all
    function get_album_gambar($id)
    {
        $this->db->where('id', $id);
        $this->db->order_by('id', 'desc');
        $result = $this->db->get('gallery')->result();

        $data = array();
        foreach ($result as $row) {
            $data[] = array(
                    'title'=>$row->title,
                    'description'=>$row->description,
                    'gambar'=>$this->get_gambar($row->id),
                );
        }

        return $data;
    }
    function get_gambar($id)
    {
        return $this->db->where('id_gallery',$id)->get('images_gallery')->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
    	$this->db->or_like('title', $q);
    	$this->db->or_like('description', $q);
    	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
    	$this->db->or_like('title', $q);
    	$this->db->or_like('description', $q);
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
        return $this->db->insert_id();
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Gallery_model.php */
/* Location: ./application/models/Gallery_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-08-18 11:08:49 */
/* http://harviacode.com */