<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Lowongan_model extends CI_Model
{

    public $table = 'lowongan';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('l.id as id,l.*,p.perusahaan');
        $this->datatables->from('lowongan as l');
        $this->datatables->join('perusahaan as p', 'p.id = l.id_perusahaan');
        $this->datatables->add_column('action', anchor(site_url('admin/lowongan/read/$1'),'Read')." | ".anchor(site_url('admin/lowongan/update/$1'),'Update')." | ".anchor(site_url('admin/lowongan/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    function get_all()
    {
        $this->db->select('l.id as id,l.*,p.perusahaan');
        $this->db->from('lowongan as l');
        $this->db->join('perusahaan as p', 'p.id = l.id_perusahaan');
        $this->db->order_by('l.id', $this->order);
        return $this->db->get()->result();
    }
    // get all active
    function get_all_active()
    {
        $this->db->select('l.id as id,l.*,p.perusahaan');
        $this->db->from('lowongan as l');
        $this->db->join('perusahaan as p', 'p.id = l.id_perusahaan');
        $this->db->where('status', '');
        $this->db->order_by('l.id', $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->select('l.id as id,l.*,p.perusahaan');
        $this->db->from('lowongan as l');
        $this->db->join('perusahaan as p', 'p.id = l.id_perusahaan');
        $this->db->where('l.id', $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->select('l.id as id,l.*,p.perusahaan');
        $this->db->join('perusahaan as p', 'p.id = l.id_perusahaan');
        $this->db->like('id', $q);
    	$this->db->or_like('id_perusahaan', $q);
    	$this->db->or_like('lowongan', $q);
    	$this->db->or_like('min_pendidikan', $q);
    	$this->db->or_like('penempatan', $q);
    	$this->db->or_like('batas_waktu', $q);
    	$this->db->or_like('detail_lowongan', $q);
    	$this->db->or_like('butuh_orang', $q);
        $this->db->from('lowongan as l');
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->select('l.id as id,l.*,p.perusahaan');
        $this->db->from('lowongan as l');
        $this->db->join('perusahaan as p', 'p.id = l.id_perusahaan');
        $this->db->order_by('l.id', $this->order);
        $this->db->like('id', $q);
    	$this->db->or_like('id_perusahaan', $q);
    	$this->db->or_like('lowongan', $q);
    	$this->db->or_like('min_pendidikan', $q);
    	$this->db->or_like('penempatan', $q);
    	$this->db->or_like('batas_waktu', $q);
    	$this->db->or_like('detail_lowongan', $q);
    	$this->db->or_like('butuh_orang', $q);
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Lowongan_model.php */
/* Location: ./application/models/Lowongan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-07-19 09:38:30 */
/* http://harviacode.com */