<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sliders_model extends CI_Model
{

    public $table = 'sliders';
    public $id = 'id';
    public $level = 'level';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id, image, level');
        $this->datatables->from('sliders');
        $this->datatables->add_column('action', anchor(site_url('admin/sliders/read/$1'),'<span class="btn btn-primary">Read</span>')." ".anchor(site_url('admin/sliders/update/$1'),'<span class="btn btn-warning">Edit</span>')." ".anchor(site_url('admin/sliders/delete/$1'),'<span class="btn btn-danger">Delete</span>','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->select('id, image, level');
        $this->db->from($this->table);
        $this->db->order_by($this->id, $this->order);
        return $this->db->get()->result();
    }

    // get all
    function get_all_order_level()
    {
        $this->db->select('id, image, level,url,title,content');
        $this->db->from($this->table);
        $this->db->order_by($this->level, 'ASC');
        return $this->db->get()->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->select('id, image, level,url,title,content');
        $this->db->from($this->table);
        $this->db->where($this->id, $id);
        return $this->db->get()->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->select('id, image, level');
        $this->db->like('id', $q);
    	$this->db->or_like('image', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->select('id, image, level');
        $this->db->like('id', $q);
        $this->db->or_like('image', $q);
        $this->db->from($this->table);
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Perusahaan_model.php */
/* Location: ./application/models/Perusahaan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-07-19 08:33:37 */
/* http://harviacode.com */