<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Testimoni_model extends CI_Model
{

    public $table = 'testimoni';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('t.id as id,id_user,u.full_name as name,isi,tanggal');
        $this->datatables->from('testimoni as t');
        $this->datatables->join('users as u', 'u.id = t.id_user');
        $this->datatables->add_column('action', anchor(site_url('admin/testimoni/read/$1'),'Read')." | ".anchor(site_url('admin/testimoni/update/$1'),'Update')." | ".anchor(site_url('admin/testimoni/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->select('t.id as id,t.id_user,u.full_name as name,t.isi,t.tanggal');
        $this->db->from('testimoni as t');
        $this->db->join('users as u', 'u.id = t.id_user');
        $this->db->order_by('t.id', $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->select('t.id as id,id_user,u.full_name as name,isi,tanggal');
        $this->db->from('testimoni as t');
        $this->db->join('users as u', 'u.id = t.id_user');
        $this->db->where('t.id', $id);
        return $this->db->get()->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->select('t.id as id,id_user,u.full_name as name,isi,tanggal');
        $this->db->join('users as u', 'u.id = t.id_user');
        $this->db->like('id', $q);
    	$this->db->or_like('id_user', $q);
    	$this->db->or_like('isi', $q);
    	$this->db->or_like('tanggal', $q);
        $this->db->from('testimoni as t');
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->select('t.id as id,id_user,u.full_name as name,isi,tanggal');
        $this->db->from('testimoni as t');
        $this->db->join('users as u', 'u.id = t.id_user');
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
    	$this->db->or_like('id_user', $q);
    	$this->db->or_like('isi', $q);
    	$this->db->or_like('tanggal', $q);
    	$this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Testimoni_model.php */
/* Location: ./application/models/Testimoni_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-07-19 10:13:55 */
/* http://harviacode.com */